services:
  # Backend NestJS
  api:
    build: .
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASS}@db:${DB_PORT}/${DB_NAME}?schema=public
      DIRECT_URL: postgresql://${DB_USER}:${DB_PASS}@db:${DB_PORT}/${DB_NAME}?schema=public
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      RESEND_API_KEY: ${RESEND_API_KEY}
      MAIL_FROM: ${MAIL_FROM}
      MAIL_TO: ${MAIL_TO}
      NODE_ENV: production
      PORT: 3000
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_DB: ${REDIS_DB}
    ports:
      - '3000:3000'
    volumes:
      - ./logs:/app/logs
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    command: >
      sh -c "npx prisma migrate deploy &&
             npx prisma db seed &&
             node dist/main.js"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Banco de Dados PostgreSQL
  db:
    image: postgis/postgis:15-3.4-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Redis para o BullMQ (Fila de Notificações)
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/data
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]

  # Ngrok para expor a API publicamente
  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    ports:
      - "4040:4040" # Para a interface web do ngrok
    environment:
      # O NGROK_AUTHTOKEN e NGROK_DOMAIN devem ser definidos em um arquivo .env
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
      - NGROK_DOMAIN=${NGROK_DOMAIN}
    command: ["http", "api:3000", "--domain=${NGROK_DOMAIN}", "--log=stdout"]
    depends_on:
      - api

volumes:
  pgdata:
  redisdata: